name: C++ doctest

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build tests
        run: |
          g++ --version
          g++ -std=c++14 -O0 -g -D_DEBUG -Wall -Wextra -pedantic -I. main.cpp -o tests

      - name: Run tests
        run: |
          ./tests